"""add price to stock_entry and consumption_log

Revision ID: 2185a443e1c0
Revises: 7fe0e9f090c1
Create Date: 2026-07-16 09:01:27.528903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2185a443e1c0'
down_revision: Union[str, Sequence[str], None] = '7fe0e9f090c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption_log', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('stock_entries', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_entries', 'price')
    op.drop_column('consumption_log', 'price')
    # ### end Alembic commands ###
