"""drop product brand column

Revision ID: 24abb35ef0bf
Revises: 25f48b0b85f0
Create Date: 2026-07-13 19:18:34.419733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24abb35ef0bf'
down_revision: Union[str, Sequence[str], None] = '25f48b0b85f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
