"""add does not spoil and expiring soon days to product

Revision ID: 356f3a01fbd5
Revises: 75047f65b399
Create Date: 2026-07-21 23:35:18.667217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356f3a01fbd5'
down_revision: Union[str, Sequence[str], None] = '75047f65b399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('does_not_spoil', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('expiring_soon_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('expiring_soon_days')
        batch_op.drop_column('does_not_spoil')

    # ### end Alembic commands ###
