"""add undo snapshot to consumption_log

Revision ID: 75047f65b399
Revises: a262b135cd96
Create Date: 2026-07-18 19:18:05.451241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75047f65b399'
down_revision: Union[str, Sequence[str], None] = 'a262b135cd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default '0' backfills every pre-existing row as NOT undoable
    # (#224): those rows never captured the snapshot undo now requires, so
    # they must not be reversible into fabricated stock. The snapshot columns
    # below stay null for them accordingly.
    op.add_column('consumption_log', sa.Column('undoable', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('consumption_log', sa.Column('undo_location_id', sa.Integer(), nullable=True))
    op.add_column('consumption_log', sa.Column('undo_best_before_date', sa.Date(), nullable=True))
    op.add_column('consumption_log', sa.Column('undo_purchased_date', sa.Date(), nullable=True))
    op.add_column('consumption_log', sa.Column('undo_opened_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumption_log', 'undo_opened_at')
    op.drop_column('consumption_log', 'undo_purchased_date')
    op.drop_column('consumption_log', 'undo_best_before_date')
    op.drop_column('consumption_log', 'undo_location_id')
    op.drop_column('consumption_log', 'undoable')
    # ### end Alembic commands ###
