"""add product target_stock_level

Revision ID: 7fe0e9f090c1
Revises: bec0c004befd
Create Date: 2026-07-14 16:08:36.322166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe0e9f090c1'
down_revision: Union[str, Sequence[str], None] = 'bec0c004befd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('target_stock_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'target_stock_level')
    # ### end Alembic commands ###
