"""add quantity_unit to consumption_log

Revision ID: bec0c004befd
Revises: a312d38c93a6
Create Date: 2026-07-14 15:43:55.568852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec0c004befd'
down_revision: Union[str, Sequence[str], None] = 'a312d38c93a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('consumption_log', sa.Column('quantity_unit', sa.String(), nullable=True))
    # Backfill existing rows from their product's *current* unit -- the best
    # available approximation, since the unit at the original write time was
    # never recorded. A correlated subquery (rather than UPDATE ... FROM) to
    # stay compatible with older SQLite versions.
    op.execute(
        """
        UPDATE consumption_log
        SET quantity_unit = (
            SELECT products.quantity_unit
            FROM products
            WHERE products.id = consumption_log.product_id
        )
        WHERE quantity_unit IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumption_log', 'quantity_unit')
    # ### end Alembic commands ###
