"""category as a real entity

Revision ID: c92c18306a9a
Revises: 4cd665553998
Create Date: 2026-07-13 21:55:48.607371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92c18306a9a'
down_revision: Union[str, Sequence[str], None] = '4cd665553998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Data migration -- turn each distinct free-text category already in use
    # into a real Category row, and point products at it, before the old
    # string column disappears (#72: category becomes a real entity).
    conn = op.get_bind()
    distinct_categories = conn.execute(
        sa.text("SELECT DISTINCT category FROM products WHERE category IS NOT NULL AND category != ''")
    ).fetchall()
    for (name,) in distinct_categories:
        conn.execute(sa.text("INSERT INTO categories (name) VALUES (:name)"), {"name": name})
    conn.execute(
        sa.text(
            """
            UPDATE products
            SET category_id = (SELECT id FROM categories WHERE categories.name = products.category)
            WHERE category IS NOT NULL AND category != ''
            """
        )
    )

    # SQLite can't ALTER a constraint onto an existing table -- batch mode
    # does the copy-and-recreate dance for us.
    with op.batch_alter_table('products') as batch_op:
        batch_op.create_foreign_key(
            'fk_products_category_id_categories', 'categories', ['category_id'], ['id']
        )
        batch_op.drop_column('category')


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('products', sa.Column('category', sa.VARCHAR(), nullable=True))

    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            UPDATE products
            SET category = (SELECT name FROM categories WHERE categories.id = products.category_id)
            WHERE category_id IS NOT NULL
            """
        )
    )

    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint('fk_products_category_id_categories', type_='foreignkey')
        batch_op.drop_column('category_id')
    op.drop_table('categories')
