"""add opened_at and default_open_shelf_life_days

Revision ID: f2f4ae42db44
Revises: fbe0815b1e40
Create Date: 2026-07-13 16:36:25.027403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f4ae42db44'
down_revision: Union[str, Sequence[str], None] = 'fbe0815b1e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('default_open_shelf_life_days', sa.Integer(), nullable=True))
    op.add_column('stock_entries', sa.Column('opened_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_entries', 'opened_at')
    op.drop_column('products', 'default_open_shelf_life_days')
    # ### end Alembic commands ###
